source "https://rubygems.org"

gem "carb-core",    path: "../../carb-core"
gem "carb-service", path: "../../carb-service"
gem "carb-flow",    path: "../../carb-flow"
gem "carb-inject",  path: "../../carb-inject"
gem "pry-byebug"
